**Predicting Sickness-related absenteeism and Risk factors associated among employees of the business unit**


Using Logistic Regression Analysis


# Creating a logistic regression to predict absenteeism

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


## Import the relevant libraries

In [0]:
# import the relevant libraries
import pandas as pd
import numpy as np

## Load the data

In [0]:
# load the preprocessed CSV data
data_preprocessed = pd.read_csv('/content/drive/My Drive/Absenteeism_preprocessed.csv')

In [4]:
# eyeball the data
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  ...  Children  Pets  Absenteeism Time in Hours
0         0         0         0  ...         2     1                          4
1         0         0         0  ...         1     0                          0
2         0         0         0  ...         0     0                          2
3         1         0         0  ...         2     0                          4
4         0         0         0  ...         2     1                          2

[5 rows x 15 columns]

## Create the targets

In [5]:
# find the median of 'Absenteeism Time in Hours'
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [0]:
# create targets for our logistic regression
# they have to be categories and we must find a way to say if someone is 'being absent too much' or not
# what we've decided to do is to take the median of the dataset as a cut-off line
# in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)
# as balancing is a great problem for ML, this will work great for us
# alternatively, if we had more data, we could have found other ways to deal with the issue 
# for instance, we could have assigned some arbitrary value as a cut-off line, instead of the median

# note that what line does is to assign 1 to anyone who has been absent 4 hours or more (more than 3 hours)
# that is the equivalent of taking half a day off

# initial code from the lecture
# targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

# parameterized code
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [7]:
# eyeball the targets
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [0]:
# create a Series in the original data frame that will contain the targets for the regression
data_preprocessed['Excessive Absenteeism'] = targets

In [9]:
# check what happened
# maybe manually see how the targets were created
data_preprocessed.head()

Reason_1  Reason_2  ...  Absenteeism Time in Hours  Excessive Absenteeism
0         0         0  ...                          4                      1
1         0         0  ...                          0                      0
2         0         0  ...                          2                      0
3         1         0  ...                          4                      1
4         0         0  ...                          2                      0

[5 rows x 16 columns]

## A comment on the targets

In [10]:
# check if dataset is balanced (what % of targets are 1s)
# targets.sum() will give us the number of 1s that there are
# the shape[0] will give us the length of the targets array
targets.sum() / targets.shape[0]

0.45571428571428574

In [0]:
# create a checkpoint by dropping the unnecessary variables
# also drop the variables we 'eliminated' after exploring the weights
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [12]:
# if data_with_targets is data_preprocessed = True, then the two are pointing to the same object
# if it is False, then the two variables are completely different and this is in fact a checkpoint
data_with_targets is data_preprocessed

False

In [13]:
# check what's inside
data_with_targets.head()

Reason_1  Reason_2  Reason_3  ...  Children  Pets  Excessive Absenteeism
0         0         0         0  ...         2     1                      1
1         0         0         0  ...         1     0                      0
2         0         0         0  ...         0     0                      0
3         1         0         0  ...         2     0                      1
4         0         0         0  ...         2     1                      0

[5 rows x 12 columns]

## Select the inputs for the regression

In [14]:
data_with_targets.shape

(700, 12)

In [16]:
# Selects all rows and all columns but the last one
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  ...  Education  Children  Pets
0           0         0         0  ...          0         2     1
1           0         0         0  ...          0         1     0
2           0         0         0  ...          0         0     0
3           1         0         0  ...          0         2     0
4           0         0         0  ...          0         2     1
..        ...       ...       ...  ...        ...       ...   ...
695         1         0         0  ...          1         2     0
696         1         0         0  ...          0         1     2
697         1         0         0  ...          1         0     0
698         0         0         0  ...          1         0     0
699         0         0         0  ...          0         1     1

[700 rows x 11 columns]

In [0]:
# a variable that will contain the inputs (everything without the targets)
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [0]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
from sklearn.preprocessing import StandardScaler


# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
absenteeism_scaler = StandardScaler()

In [0]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [20]:
# check what are all columns that we've got
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [0]:
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [0]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [0]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

In [24]:
# fit the data (calculate mean and standard deviation); they are automatically stored inside the object 
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [0]:
# standardizes the data, using the transform method 
# in the last line, we fitted the data - in other words
# we found the internal parameters of a model that will be used to transform data. 
# transforming applies these parameters to our data
# note that when you get new data, you can just call 'scaler' again and transform it in the same way as now
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [26]:
# the scaled_inputs are now an ndarray, because sklearn works with ndarrays
scaled_inputs

Reason_1  Reason_2  Reason_3  ...  Education  Children      Pets
0           0         0         0  ...          0  0.880469  0.268487
1           0         0         0  ...          0 -0.019280 -0.589690
2           0         0         0  ...          0 -0.919030 -0.589690
3           1         0         0  ...          0  0.880469 -0.589690
4           0         0         0  ...          0  0.880469  0.268487
..        ...       ...       ...  ...        ...       ...       ...
695         1         0         0  ...          1  0.880469 -0.589690
696         1         0         0  ...          0 -0.019280  1.126663
697         1         0         0  ...          1 -0.919030 -0.589690
698         0         0         0  ...          1 -0.919030 -0.589690
699         0         0         0  ...          0 -0.019280  0.268487

[700 rows x 11 columns]

In [27]:
# check the shape of the inputs
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

In [0]:
# import train_test_split so we can split our data into train and test
from sklearn.model_selection import train_test_split

### Split

In [29]:
# check how this method works
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  ...  Education  Children      Pets
 348         0         0         0  ...          1 -0.919030 -0.589690
 272         0         0         1  ...          0  0.880469  0.268487
 632         0         0         0  ...          0 -0.919030 -0.589690
 46          0         0         0  ...          0 -0.919030 -0.589690
 207         0         0         1  ...          0 -0.919030 -0.589690
 ..        ...       ...       ...  ...        ...       ...       ...
 280         0         0         0  ...          0 -0.919030 -0.589690
 441         0         0         0  ...          0 -0.919030 -0.589690
 367         0         0         0  ...          0 -0.919030 -0.589690
 204         1         0         0  ...          0  0.880469  0.268487
 552         0         0         0  ...          0 -0.019280  1.126663
 
 [525 rows x 11 columns],
      Reason_1  Reason_2  Reason_3  ...  Education  Children      Pets
 385         0         0         0  ...          

In [0]:
# declare 4 variables for the split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [31]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [32]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic regression with sklearn

In [0]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

### Training the model

In [0]:
# create a logistic regression object
reg = LogisticRegression()

In [35]:
# fit our train inputs
# that is basically the whole training part of the machine learning
reg.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

0.775

### Finding the intercept and coefficients

In [43]:
# get the intercept (bias) of our model
reg.intercept_

array([-1.46547112])

In [44]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 2.62749942,  0.86338637,  2.96050661,  0.66390745,  0.15493732,
         0.59979822, -0.17245127,  0.27568526, -0.23452541,  0.34249662,
        -0.2775137 ]])

In [49]:
# check what were the names of our columns
scaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [0]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [50]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

Feature name  Coefficient
0                 Reason_1     2.627499
1                 Reason_2     0.863386
2                 Reason_3     2.960507
3                 Reason_4     0.663907
4              Month Value     0.154937
5   Transportation Expense     0.599798
6                      Age    -0.172451
7          Body Mass Index     0.275685
8                Education    -0.234525
9                 Children     0.342497
10                    Pets    -0.277514

In [51]:
# do a little Python trick to move the intercept to the top of the summary table
# move all indices by 1
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.465471
1                 Reason_1     2.627499
2                 Reason_2     0.863386
3                 Reason_3     2.960507
4                 Reason_4     0.663907
5              Month Value     0.154937
6   Transportation Expense     0.599798
7                      Age    -0.172451
8          Body Mass Index     0.275685
9                Education    -0.234525
10                Children     0.342497
11                    Pets    -0.277514

## Interpreting the coefficients

In [0]:
# create a new Series called: 'Odds ratio' which will show the.. odds ratio of each feature
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [53]:
# display the df
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.465471    0.230969
1                 Reason_1     2.627499   13.839121
2                 Reason_2     0.863386    2.371177
3                 Reason_3     2.960507   19.307751
4                 Reason_4     0.663907    1.942367
5              Month Value     0.154937    1.167585
6   Transportation Expense     0.599798    1.821751
7                      Age    -0.172451    0.841599
8          Body Mass Index     0.275685    1.317433
9                Education    -0.234525    0.790946
10                Children     0.342497    1.408460
11                    Pets    -0.277514    0.757665

In [54]:
# sort the table according to odds ratio
# note that by default, the sort_values method sorts values by 'ascending'
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     2.960507   19.307751
1                 Reason_1     2.627499   13.839121
2                 Reason_2     0.863386    2.371177
4                 Reason_4     0.663907    1.942367
6   Transportation Expense     0.599798    1.821751
10                Children     0.342497    1.408460
8          Body Mass Index     0.275685    1.317433
5              Month Value     0.154937    1.167585
7                      Age    -0.172451    0.841599
9                Education    -0.234525    0.790946
11                    Pets    -0.277514    0.757665
0                Intercept    -1.465471    0.230969

## Testing the model

In [55]:
# assess the test accuracy of the model
reg.score(x_test,y_test)

0.75

In [56]:
# find the predicted probabilities of each class
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)

# let's check that out
predicted_proba

array([[0.71221976, 0.28778024],
       [0.58760009, 0.41239991],
       [0.44337438, 0.55662562],
       [0.77903962, 0.22096038],
       [0.08458343, 0.91541657],
       [0.33103371, 0.66896629],
       [0.29792496, 0.70207504],
       [0.12956221, 0.87043779],
       [0.78307821, 0.21692179],
       [0.74708659, 0.25291341],
       [0.49514969, 0.50485031],
       [0.22640297, 0.77359703],
       [0.07030984, 0.92969016],
       [0.73504052, 0.26495948],
       [0.30533085, 0.69466915],
       [0.55035881, 0.44964119],
       [0.55027426, 0.44972574],
       [0.53930442, 0.46069558],
       [0.40117774, 0.59882226],
       [0.05320682, 0.94679318],
       [0.69874615, 0.30125385],
       [0.77903962, 0.22096038],
       [0.41634563, 0.58365437],
       [0.41634563, 0.58365437],
       [0.2412915 , 0.7587085 ],
       [0.74317087, 0.25682913],
       [0.51065194, 0.48934806],
       [0.85703303, 0.14296697],
       [0.19934235, 0.80065765],
       [0.77903962, 0.22096038],
       [0.

In [57]:
predicted_proba.shape

(140, 2)

In [58]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.28778024, 0.41239991, 0.55662562, 0.22096038, 0.91541657,
       0.66896629, 0.70207504, 0.87043779, 0.21692179, 0.25291341,
       0.50485031, 0.77359703, 0.92969016, 0.26495948, 0.69466915,
       0.44964119, 0.44972574, 0.46069558, 0.59882226, 0.94679318,
       0.30125385, 0.22096038, 0.58365437, 0.58365437, 0.7587085 ,
       0.25682913, 0.48934806, 0.14296697, 0.80065765, 0.22096038,
       0.37028423, 0.68316787, 0.68825755, 0.52694241, 0.22096038,
       0.53492642, 0.22453007, 0.74389237, 0.40329273, 0.60301627,
       0.21343976, 0.45483346, 0.2403088 , 0.4388431 , 0.82622935,
       0.57857132, 0.69461059, 0.28778024, 0.22209028, 0.2061074 ,
       0.57577123, 0.36438663, 0.66896629, 0.27128561, 0.83334736,
       0.43399232, 0.88600663, 0.23396355, 0.37170685, 0.38209505,
       0.69796139, 0.65909803, 0.29392197, 0.79686146, 0.20956093,
       0.2699923 , 0.10399887, 0.22453007, 0.73944244, 0.30081832,
       0.22453007, 0.32688766, 0.90337554, 0.45745729, 0.59997

## Save the model

In [0]:
# import the relevant module
import pickle  # convert python object to character stream

In [0]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [0]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)